export default [
  { id: "AF", label: "Afghanistan", group: "Asia" },
  { id: "AX", label: "Åland Islands", group: "Europe" },
  { id: "AL", label: "Albania", group: "Europe" },
  { id: "DZ", label: "Algeria", group: "Africa" },
  { id: "AS", label: "American Samoa", group: "Oceania" },
  { id: "AD", label: "Andorra", group: "Europe" },
  { id: "AO", label: "Angola", group: "Africa" },
  { id: "AI", label: "Anguilla", group: "Americas" },
  { id: "AQ", label: "Antarctica", group: "" },
  { id: "AG", label: "Antigua and Barbuda", group: "Americas" },
  { id: "AR", label: "Argentina", group: "Americas" },
  { id: "AM", label: "Armenia", group: "Asia" },
  { id: "AW", label: "Aruba", group: "Americas" },
  { id: "AU", label: "Australia", group: "Oceania" },
  { id: "AT", label: "Austria", group: "Europe" },
  { id: "AZ", label: "Azerbaijan", group: "Asia" },
  { id: "BS", label: "Bahamas", group: "Americas" },
  { id: "BH", label: "Bahrain", group: "Asia" },
  { id: "BD", label: "Bangladesh", group: "Asia" },
  { id: "BB", label: "Barbados", group: "Americas" },
  { id: "BY", label: "Belarus", group: "Europe" },
  { id: "BE", label: "Belgium", group: "Europe" },
  { id: "BZ", label: "Belize", group: "Americas" },
  { id: "BJ", label: "Benin", group: "Africa" },
  { id: "BM", label: "Bermuda", group: "Americas" },
  { id: "BT", label: "Bhutan", group: "Asia" },
  { id: "BO", label: "Bolivia, Plurinational State of", group: "Americas" },
  { id: "BQ", label: "Bonaire, Sint Eustatius and Saba", group: "Americas" },
  { id: "BA", label: "Bosnia and Herzegovina", group: "Europe" },
  { id: "BW", label: "Botswana", group: "Africa" },
  { id: "BV", label: "Bouvet Island", group: "Americas" },
  { id: "BR", label: "Brazil", group: "Americas" },
  { id: "IO", label: "British Indian Ocean Territory", group: "Africa" },
  { id: "BN", label: "Brunei Darussalam", group: "Asia" },
  { id: "BG", label: "Bulgaria", group: "Europe" },
  { id: "BF", label: "Burkina Faso", group: "Africa" },
  { id: "BI", label: "Burundi", group: "Africa" },
  { id: "CV", label: "Cabo Verde", group: "Africa" },
  { id: "KH", label: "Cambodia", group: "Asia" },
  { id: "CM", label: "Cameroon", group: "Africa" },
  { id: "CA", label: "Canada", group: "Americas" },
  { id: "KY", label: "Cayman Islands", group: "Americas" },
  { id: "CF", label: "Central African Republic", group: "Africa" },
  { id: "TD", label: "Chad", group: "Africa" },
  { id: "CL", label: "Chile", group: "Americas" },
  { id: "CN", label: "China", group: "Asia" },
  { id: "CX", label: "Christmas Island", group: "Oceania" },
  { id: "CC", label: "Cocos (Keeling) Islands", group: "Oceania" },
  { id: "CO", label: "Colombia", group: "Americas" },
  { id: "KM", label: "Comoros", group: "Africa" },
  { id: "CG", label: "Congo", group: "Africa" },
  { id: "CD", label: "Congo, Democratic Republic of the", group: "Africa" },
  { id: "CK", label: "Cook Islands", group: "Oceania" },
  { id: "CR", label: "Costa Rica", group: "Americas" },
  { id: "CI", label: "Côte d'Ivoire", group: "Africa" },
  { id: "HR", label: "Croatia", group: "Europe" },
  { id: "CU", label: "Cuba", group: "Americas" },
  { id: "CW", label: "Curaçao", group: "Americas" },
  { id: "CY", label: "Cyprus", group: "Asia" },
  { id: "CZ", label: "Czechia", group: "Europe" },
  { id: "DK", label: "Denmark", group: "Europe" },
  { id: "DJ", label: "Djibouti", group: "Africa" },
  { id: "DM", label: "Dominica", group: "Americas" },
  { id: "DO", label: "Dominican Republic", group: "Americas" },
  { id: "EC", label: "Ecuador", group: "Americas" },
  { id: "EG", label: "Egypt", group: "Africa" },
  { id: "SV", label: "El Salvador", group: "Americas" },
  { id: "GQ", label: "Equatorial Guinea", group: "Africa" },
  { id: "ER", label: "Eritrea", group: "Africa" },
  { id: "EE", label: "Estonia", group: "Europe" },
  { id: "SZ", label: "Eswatini", group: "Africa" },
  { id: "ET", label: "Ethiopia", group: "Africa" },
  { id: "FK", label: "Falkland Islands (Malvinas)", group: "Americas" },
  { id: "FO", label: "Faroe Islands", group: "Europe" },
  { id: "FJ", label: "Fiji", group: "Oceania" },
  { id: "FI", label: "Finland", group: "Europe" },
  { id: "FR", label: "France", group: "Europe" },
  { id: "GF", label: "French Guiana", group: "Americas" },
  { id: "PF", label: "French Polynesia", group: "Oceania" },
  { id: "TF", label: "French Southern Territories", group: "Africa" },
  { id: "GA", label: "Gabon", group: "Africa" },
  { id: "GM", label: "Gambia", group: "Africa" },
  { id: "GE", label: "Georgia", group: "Asia" },
  { id: "DE", label: "Germany", group: "Europe" },
  { id: "GH", label: "Ghana", group: "Africa" },
  { id: "GI", label: "Gibraltar", group: "Europe" },
  { id: "GR", label: "Greece", group: "Europe" },
  { id: "GL", label: "Greenland", group: "Americas" },
  { id: "GD", label: "Grenada", group: "Americas" },
  { id: "GP", label: "Guadeloupe", group: "Americas" },
  { id: "GU", label: "Guam", group: "Oceania" },
  { id: "GT", label: "Guatemala", group: "Americas" },
  { id: "GG", label: "Guernsey", group: "Europe" },
  { id: "GN", label: "Guinea", group: "Africa" },
  { id: "GW", label: "Guinea-Bissau", group: "Africa" },
  { id: "GY", label: "Guyana", group: "Americas" },
  { id: "HT", label: "Haiti", group: "Americas" },
  { id: "HM", label: "Heard Island and McDonald Islands", group: "Oceania" },
  { id: "VA", label: "Holy See", group: "Europe" },
  { id: "HN", label: "Honduras", group: "Americas" },
  { id: "HK", label: "Hong Kong", group: "Asia" },
  { id: "HU", label: "Hungary", group: "Europe" },
  { id: "IS", label: "Iceland", group: "Europe" },
  { id: "IN", label: "India", group: "Asia" },
  { id: "ID", label: "Indonesia", group: "Asia" },
  { id: "IR", label: "Iran, Islamic Republic of", group: "Asia" },
  { id: "IQ", label: "Iraq", group: "Asia" },
  { id: "IE", label: "Ireland", group: "Europe" },
  { id: "IM", label: "Isle of Man", group: "Europe" },
  { id: "IL", label: "Israel", group: "Asia" },
  { id: "IT", label: "Italy", group: "Europe" },
  { id: "JM", label: "Jamaica", group: "Americas" },
  { id: "JP", label: "Japan", group: "Asia" },
  { id: "JE", label: "Jersey", group: "Europe" },
  { id: "JO", label: "Jordan", group: "Asia" },
  { id: "KZ", label: "Kazakhstan", group: "Asia" },
  { id: "KE", label: "Kenya", group: "Africa" },
  { id: "KI", label: "Kiribati", group: "Oceania" },
  { id: "KP", label: "Korea, Democratic People's Republic of", group: "Asia" },
  { id: "KR", label: "Korea, Republic of", group: "Asia" },
  { id: "KW", label: "Kuwait", group: "Asia" },
  { id: "KG", label: "Kyrgyzstan", group: "Asia" },
  { id: "LA", label: "Lao People's Democratic Republic", group: "Asia" },
  { id: "LV", label: "Latvia", group: "Europe" },
  { id: "LB", label: "Lebanon", group: "Asia" },
  { id: "LS", label: "Lesotho", group: "Africa" },
  { id: "LR", label: "Liberia", group: "Africa" },
  { id: "LY", label: "Libya", group: "Africa" },
  { id: "LI", label: "Liechtenstein", group: "Europe" },
  { id: "LT", label: "Lithuania", group: "Europe" },
  { id: "LU", label: "Luxembourg", group: "Europe" },
  { id: "MO", label: "Macao", group: "Asia" },
  { id: "MG", label: "Madagascar", group: "Africa" },
  { id: "MW", label: "Malawi", group: "Africa" },
  { id: "MY", label: "Malaysia", group: "Asia" },
  { id: "MV", label: "Maldives", group: "Asia" },
  { id: "ML", label: "Mali", group: "Africa" },
  { id: "MT", label: "Malta", group: "Europe" },
  { id: "MH", label: "Marshall Islands", group: "Oceania" },
  { id: "MQ", label: "Martinique", group: "Americas" },
  { id: "MR", label: "Mauritania", group: "Africa" },
  { id: "MU", label: "Mauritius", group: "Africa" },
  { id: "YT", label: "Mayotte", group: "Africa" },
  { id: "MX", label: "Mexico", group: "Americas" },
  { id: "FM", label: "Micronesia, Federated States of", group: "Oceania" },
  { id: "MD", label: "Moldova, Republic of", group: "Europe" },
  { id: "MC", label: "Monaco", group: "Europe" },
  { id: "MN", label: "Mongolia", group: "Asia" },
  { id: "ME", label: "Montenegro", group: "Europe" },
  { id: "MS", label: "Montserrat", group: "Americas" },
  { id: "MA", label: "Morocco", group: "Africa" },
  { id: "MZ", label: "Mozambique", group: "Africa" },
  { id: "MM", label: "Myanmar", group: "Asia" },
  { id: "NA", label: "Namibia", group: "Africa" },
  { id: "NR", label: "Nauru", group: "Oceania" },
  { id: "NP", label: "Nepal", group: "Asia" },
  { id: "NL", label: "Netherlands, Kingdom of the", group: "Europe" },
  { id: "NC", label: "New Caledonia", group: "Oceania" },
  { id: "NZ", label: "New Zealand", group: "Oceania" },
  { id: "NI", label: "Nicaragua", group: "Americas" },
  { id: "NE", label: "Niger", group: "Africa" },
  { id: "NG", label: "Nigeria", group: "Africa" },
  { id: "NU", label: "Niue", group: "Oceania" },
  { id: "NF", label: "Norfolk Island", group: "Oceania" },
  { id: "MK", label: "North Macedonia", group: "Europe" },
  { id: "MP", label: "Northern Mariana Islands", group: "Oceania" },
  { id: "NO", label: "Norway", group: "Europe" },
  { id: "OM", label: "Oman", group: "Asia" },
  { id: "PK", label: "Pakistan", group: "Asia" },
  { id: "PW", label: "Palau", group: "Oceania" },
  { id: "PS", label: "Palestine, State of", group: "Asia" },
  { id: "PA", label: "Panama", group: "Americas" },
  { id: "PG", label: "Papua New Guinea", group: "Oceania" },
  { id: "PY", label: "Paraguay", group: "Americas" },
  { id: "PE", label: "Peru", group: "Americas" },
  { id: "PH", label: "Philippines", group: "Asia" },
  { id: "PN", label: "Pitcairn", group: "Oceania" },
  { id: "PL", label: "Poland", group: "Europe" },
  { id: "PT", label: "Portugal", group: "Europe" },
  { id: "PR", label: "Puerto Rico", group: "Americas" },
  { id: "QA", label: "Qatar", group: "Asia" },
  { id: "RE", label: "Réunion", group: "Africa" },
  { id: "RO", label: "Romania", group: "Europe" },
  { id: "RU", label: "Russian Federation", group: "Europe" },
  { id: "RW", label: "Rwanda", group: "Africa" },
  { id: "BL", label: "Saint Barthélemy", group: "Americas" },
  {
    id: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    group: "Africa",
  },
  { id: "KN", label: "Saint Kitts and Nevis", group: "Americas" },
  { id: "LC", label: "Saint Lucia", group: "Americas" },
  { id: "MF", label: "Saint Martin (French part)", group: "Americas" },
  { id: "PM", label: "Saint Pierre and Miquelon", group: "Americas" },
  { id: "VC", label: "Saint Vincent and the Grenadines", group: "Americas" },
  { id: "WS", label: "Samoa", group: "Oceania" },
  { id: "SM", label: "San Marino", group: "Europe" },
  { id: "ST", label: "Sao Tome and Principe", group: "Africa" },
  { id: "SA", label: "Saudi Arabia", group: "Asia" },
  { id: "SN", label: "Senegal", group: "Africa" },
  { id: "RS", label: "Serbia", group: "Europe" },
  { id: "SC", label: "Seychelles", group: "Africa" },
  { id: "SL", label: "Sierra Leone", group: "Africa" },
  { id: "SG", label: "Singapore", group: "Asia" },
  { id: "SX", label: "Sint Maarten (Dutch part)", group: "Americas" },
  { id: "SK", label: "Slovakia", group: "Europe" },
  { id: "SI", label: "Slovenia", group: "Europe" },
  { id: "SB", label: "Solomon Islands", group: "Oceania" },
  { id: "SO", label: "Somalia", group: "Africa" },
  { id: "ZA", label: "South Africa", group: "Africa" },
  {
    id: "GS",
    label: "South Georgia and the South Sandwich Islands",
    group: "Americas",
  },
  { id: "SS", label: "South Sudan", group: "Africa" },
  { id: "ES", label: "Spain", group: "Europe" },
  { id: "LK", label: "Sri Lanka", group: "Asia" },
  { id: "SD", label: "Sudan", group: "Africa" },
  { id: "SR", label: "Suriname", group: "Americas" },
  { id: "SJ", label: "Svalbard and Jan Mayen", group: "Europe" },
  { id: "SE", label: "Sweden", group: "Europe" },
  { id: "CH", label: "Switzerland", group: "Europe" },
  { id: "SY", label: "Syrian Arab Republic", group: "Asia" },
  { id: "TW", label: "Taiwan, Province of China", group: "" },
  { id: "TJ", label: "Tajikistan", group: "Asia" },
  { id: "TZ", label: "Tanzania, United Republic of", group: "Africa" },
  { id: "TH", label: "Thailand", group: "Asia" },
  { id: "TL", label: "Timor-Leste", group: "Asia" },
  { id: "TG", label: "Togo", group: "Africa" },
  { id: "TK", label: "Tokelau", group: "Oceania" },
  { id: "TO", label: "Tonga", group: "Oceania" },
  { id: "TT", label: "Trinidad and Tobago", group: "Americas" },
  { id: "TN", label: "Tunisia", group: "Africa" },
  { id: "TR", label: "Türkiye", group: "Asia" },
  { id: "TM", label: "Turkmenistan", group: "Asia" },
  { id: "TC", label: "Turks and Caicos Islands", group: "Americas" },
  { id: "TV", label: "Tuvalu", group: "Oceania" },
  { id: "UG", label: "Uganda", group: "Africa" },
  { id: "UA", label: "Ukraine", group: "Europe" },
  { id: "AE", label: "United Arab Emirates", group: "Asia" },
  {
    id: "GB",
    label: "United Kingdom of Great Britain and Northern Ireland",
    group: "Europe",
  },
  { id: "US", label: "United States of America", group: "Americas" },
  { id: "UM", label: "United States Minor Outlying Islands", group: "Oceania" },
  { id: "UY", label: "Uruguay", group: "Americas" },
  { id: "UZ", label: "Uzbekistan", group: "Asia" },
  { id: "VU", label: "Vanuatu", group: "Oceania" },
  { id: "VE", label: "Venezuela, Bolivarian Republic of", group: "Americas" },
  { id: "VN", label: "Viet Nam", group: "Asia" },
  { id: "VG", label: "Virgin Islands (British)", group: "Americas" },
  { id: "VI", label: "Virgin Islands (U.S.)", group: "Americas" },
  { id: "WF", label: "Wallis and Futuna", group: "Oceania" },
  { id: "EH", label: "Western Sahara", group: "Africa" },
  { id: "YE", label: "Yemen", group: "Asia" },
  { id: "ZM", label: "Zambia", group: "Africa" },
  { id: "ZW", label: "Zimbabwe", group: "Africa" },
];
